name: Ruby

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build Jekyll site
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        JEKYLL_ENV=production bundle exec jekyll build
